language: scala
scala:
- 2.11.2
deploy:
  provider: heroku
  api_key:
    secure: WSpNUY3fJ9jzUnXLOWCl/Zk3710xNQklmz83VIol7I6nQDu743qZmB2EW4WE91IGIltf8Qk+8mZ9RYi3hdgdRB7+erz0rWXvZzvbXMed1rZEKc4se2uJb0AeXb2kgL0/AFIrIyT1rG9raHtxxTDK88Je7smYVDAQ9j4ghK5r3Fs=
  app: lunchmonkeytest
  on:
    repo: spoertsch/lunchmonkey
